### ISSUE TITLE
Link directly to recipients on grants page

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/unitary-fund#77]
I was referring someone who won a microgrant and could only link the page https://unitary.fund/grants.html. From this it's a bit hard to find their name because there are a lot of names now (a good thing!). But it would be nice to be able to do something like

`https://unitary.fund/grants.html#this-grant-recipient`

which scrolls to them. (There probably is a name for this in html but I don't know it.)

**Comment by nathanshammah** [comment]
We can implement anchors, however I did not find a way (in my very limited knowledge of html close to none) a way to *show* the anchor also to the webpage reader. Something like on Wikipedia or Read the Docs, where, if you pass on top of a subtitle with the mouse, you see the link symbol and the url gets updated to include the anchor name after the #.

**Comment by crazy4pi314** [comment]
I think this would be the way to do it as @nathanshammah suggests:
https://electrictoolbox.com/add-offsite-link-icon-after-external-links-css/

**Comment by natestemen** [comment]
Since this is not super discoverable, I wanted to document it here. If you click the yellow boxes beside each grant, the grant should snap to the top of your screen and the URL should be appended with an anchor which you can then copy and send to someone. Opening the associated URL should scroll the page to the associated anchor.

<img width="541" alt="Screenshot 2023-03-03 at 5 33 24 PM" src="https://user-images.githubusercontent.com/12703123/222868522-1f90374e-6622-4478-8488-e19e90f4f61d.png">

I tried to get a 🔗 icon showing on hover, but my CSS is not that good, and figured this is good enough, especially since we are redoing the website soon.

cc @willzeng @beecastanon
